using LoveAndHonor.Sim.Data;

namespace LoveAndHonor.Sim.View;

/// <summary>data/building_recipes.json: how buildings are assembled from the Georgian kit (§28.1a).</summary>
public sealed class BuildingRecipesConfig
{
    public DefaultsSection Defaults { get; init; } = new();
    public Dictionary<string, WindowStyle> WindowStyles { get; init; } = [];
    /// <summary>Wall finish → palette colour spec (replaces the kit's pal_brick_1). Keys starting with '_' are comments.</summary>
    public Dictionary<string, string> Walls { get; init; } = [];
    public Dictionary<string, Recipe> Recipes { get; init; } = [];
    /// <summary>timeline id → recipe id. Keys starting with '_' are comments.</summary>
    public Dictionary<string, string> RealBuildings { get; init; } = [];

    public sealed class DefaultsSection
    {
        public float MarginM { get; init; }
        public float RoofOverhangM { get; init; }
        public float CorniceHeightM { get; init; }
        public float PlinthExtraM { get; init; }
        public float MassingDistanceM { get; init; }
    }

    public sealed class WindowStyle
    {
        public int Cols { get; init; }
        public int RowsUpper { get; init; }
        public int RowsLower { get; init; }
    }

    public sealed class Recipe
    {
        public ShapeSection Shape { get; init; } = new();
        public int Storeys { get; init; } = 1;
        public string Walls { get; init; } = "brick";
        public RoofSection Roof { get; init; } = new();
        public string Windows { get; init; } = "6over6";
        public bool Quoins { get; init; }
        public bool BeltCourses { get; init; }
        public string Door { get; init; } = "front";
        public int PorticoBays { get; init; }
        public bool Cupola { get; init; }
        public int Chimneys { get; init; }
        public bool Verified { get; init; }
    }

    public sealed class ShapeSection
    {
        public string Type { get; init; } = "rect";
        public float WingWidth { get; init; } = 0.4f;
        public float WingDepth { get; init; } = 0.5f;
    }

    public sealed class RoofSection
    {
        public string Type { get; init; } = "hip";
        public float PitchDeg { get; init; } = 30;
    }

    public const string File = "building_recipes.json";

    public static BuildingRecipesConfig Load(IDataSource source) => SimJson.Parse<BuildingRecipesConfig>(source.ReadText(File), File);

    /// <summary>The recipe drawn for a timeline building, or null if it's drawn as a plain block.</summary>
    public string? RecipeForTimeline(string timelineId) =>
        !timelineId.StartsWith('_') && RealBuildings.TryGetValue(timelineId, out var r) ? r : null;
}

/// <summary>One kit piece in building space: rotate about +Y by <see cref="YawDeg"/> (Godot's convention: +X turns toward
/// −Z), scale, then move to the position.</summary>
public readonly record struct PiecePlacement(string Piece, float X, float Y, float Z, float YawDeg, float ScaleX = 1, float ScaleY = 1, float ScaleZ = 1);

/// <summary>Triangles generated by the assembler (roofs, gables, plinth, scaffolding, the far block), with flat normals.
/// Triangles are counter-clockwise seen from outside; the Godot bridge flips them to Godot's clockwise order.</summary>
public sealed class MeshBuffer
{
    public readonly List<float> Positions = [];
    public readonly List<float> Normals = [];

    public int TriangleCount => Positions.Count / 9;

    public void Tri((float X, float Y, float Z) a, (float X, float Y, float Z) b, (float X, float Y, float Z) c)
    {
        float ux = b.X - a.X, uy = b.Y - a.Y, uz = b.Z - a.Z, vx = c.X - a.X, vy = c.Y - a.Y, vz = c.Z - a.Z;
        float nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
        float len = MathF.Sqrt(nx * nx + ny * ny + nz * nz);
        if (len < 1e-9f) return;
        nx /= len; ny /= len; nz /= len;
        foreach (var p in new[] { a, b, c })
        {
            Positions.Add(p.X); Positions.Add(p.Y); Positions.Add(p.Z);
            Normals.Add(nx); Normals.Add(ny); Normals.Add(nz);
        }
    }

    public void Quad((float, float, float) a, (float, float, float) b, (float, float, float) c, (float, float, float) d)
    {
        Tri(a, b, c);
        Tri(a, c, d);
    }

    /// <summary>Axis-aligned box, all six faces outward.</summary>
    public void Box(float x0, float y0, float z0, float x1, float y1, float z1)
    {
        Quad((x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)); // +z
        Quad((x1, y0, z0), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0)); // -z
        Quad((x1, y0, z1), (x1, y0, z0), (x1, y1, z0), (x1, y1, z1)); // +x
        Quad((x0, y0, z0), (x0, y0, z1), (x0, y1, z1), (x0, y1, z0)); // -x
        Quad((x0, y1, z1), (x1, y1, z1), (x1, y1, z0), (x0, y1, z0)); // +y
        Quad((x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)); // -y
    }
}

/// <summary>A building assembled from the kit: piece placements plus generated surfaces, keyed by pipeline material name
/// (pal_* / mat_*; the kit's wall brick is <see cref="BuildingAssembler.WallMaterial"/>, recoloured by the recipe).</summary>
public sealed class AssembledBuilding
{
    public required BuildingRecipesConfig.Recipe Recipe { get; init; }
    public required float WidthM { get; init; }
    public required float DepthM { get; init; }
    public List<PiecePlacement> Pieces { get; } = [];
    public Dictionary<string, MeshBuffer> Generated { get; } = [];
    /// <summary>The simple far-away block (walls + roof), drawn beyond massing_distance_m.</summary>
    public Dictionary<string, MeshBuffer> Massing { get; } = [];
    public float WallTopY { get; set; }
    public float RidgeY { get; set; }
    /// <summary>Wall outline (x, z pairs), outward normal on the left of each edge as seen in plan with z toward the front.</summary>
    public (float X, float Z)[] Outline { get; set; } = [];

    public MeshBuffer Surface(string material) => Generated.TryGetValue(material, out var b) ? b : Generated[material] = new MeshBuffer();
    public MeshBuffer MassingSurface(string material) => Massing.TryGetValue(material, out var b) ? b : Massing[material] = new MeshBuffer();
}

/// <summary>
/// The procedural kit assembler (§28.1a, Phase 1 1f): builds a building from a recipe and a size. Rectangles and
/// L-shapes; wall bays fitted to each wall (whole bays, stretched a little), windows on every bay but the door bay,
/// quoins and cornice corners on outer corners, belt courses, a hip or gable roof (L-shapes: two hip roofs that merge),
/// gable end walls, chimneys, a portico of 1 or 3 bays with steps, a cupola, a stone plinth down to the lowest ground,
/// scaffolding while under construction, and a simple block for distance. Engine-agnostic and deterministic.
///
/// Building space: origin at the centre of the footprint at floor level, +Y up, +Z toward the front (the entrance side;
/// south when the building isn't turned), +X to the right seen from the front. Kit pieces follow docs/ART_PIPELINE.md:
/// wall pieces' pivot at the bottom-left of the outer face, outer face toward +Z.
/// </summary>
public static class BuildingAssembler
{
    public const string WallMaterial = "pal_brick_1";
    public const string Roof = "pal_slate";
    public const string Stone = "pal_limestone";
    public const string Wood = "mat_wood";

    public const string WallPlain = "kit_georgian_wall_plain_3m";
    public const string WallWindow = "kit_georgian_wall_opening_window_3m";
    public const string WallDoor = "kit_georgian_wall_opening_door_3m";
    public const string WallBase = "kit_georgian_wall_base_3m";
    public const string Quoin = "kit_georgian_corner_quoin";
    public const string Cornice = "kit_georgian_cornice_3m";
    public const string CorniceCorner = "kit_georgian_cornice_corner";
    public const string BeltCourse = "kit_georgian_beltcourse_3m";
    public const string Column = "kit_georgian_column_doric";
    public const string Pediment = "kit_georgian_pediment_3bay";
    public const string Steps = "kit_georgian_portico_steps_3m";
    public const string CupolaPiece = "kit_georgian_cupola_small";
    public const string Chimney = "kit_georgian_chimney_single";

    /// <summary>
    /// Middle distance (between the bldg category's first two LOD distances and massing_distance_m): pieces with an
    /// _LOD1 use it; these pieces stay as they are (they shape the silhouette); every other piece is left out.
    /// </summary>
    public static bool KeptAtDistance(string piece) =>
        piece is WallPlain or Cornice or Chimney or CupolaPiece or Column or Pediment;

    /// <summary>Kit sizes the assembler relies on (match tools/blender/make_kit_v1.py).</summary>
    private const float PedimentHalfWidth = 4.8f, PedimentDepth = 2.6f, ColumnHeight = 6f, MinWindowBay = 2.0f;

    /// <param name="widthM">Size along building X (left–right seen from the front).</param>
    /// <param name="depthM">Size along building Z (front–back).</param>
    /// <param name="plinthDepthM">How far the stone plinth reaches below the floor (to the lowest ground under it).</param>
    /// <param name="progress">Construction progress 0..1 (1 = finished: no scaffolding).</param>
    public static AssembledBuilding Assemble(BuildingRecipesConfig cfg, BuildingRecipesConfig.Recipe recipe, float widthM, float depthM,
        float bayM, float storeyM, float plinthDepthM = 0.5f, float progress = 1f)
    {
        var b = new AssembledBuilding { Recipe = recipe, WidthM = widthM, DepthM = depthM };
        var d = cfg.Defaults;
        float w = Math.Max(widthM, bayM), dd = Math.Max(depthM, bayM);
        int storeys = Math.Max(1, recipe.Storeys);
        float wallTop = storeys * storeyM;
        float eave = wallTop + d.CorniceHeightM;
        b.WallTopY = wallTop;

        // Plan: the outline and the rectangles the roof covers.
        var outline = new List<(float X, float Z)>();
        var roofRects = new List<(float X0, float Z0, float X1, float Z1)>();
        if (recipe.Shape.Type == "l")
        {
            float ww = Math.Max(bayM, w * recipe.Shape.WingWidth), dm = Math.Max(bayM, dd * (1 - recipe.Shape.WingDepth));
            outline.AddRange([(-w / 2, dd / 2), (w / 2, dd / 2), (w / 2, dd / 2 - dm), (-w / 2 + ww, dd / 2 - dm), (-w / 2 + ww, -dd / 2), (-w / 2, -dd / 2)]);
            roofRects.Add((-w / 2, dd / 2 - dm, w / 2, dd / 2));
            roofRects.Add((-w / 2, -dd / 2, -w / 2 + ww, dd / 2 - dm / 2)); // reaches under the main roof's ridge
        }
        else
        {
            outline.AddRange([(-w / 2, dd / 2), (w / 2, dd / 2), (w / 2, -dd / 2), (-w / 2, -dd / 2)]);
            roofRects.Add((-w / 2, -dd / 2, w / 2, dd / 2));
        }
        b.Outline = [.. outline];
        int n = outline.Count;

        // Construction stages: walls rise storey by storey, then the roof, then the details.
        float wallsFrac = Math.Clamp(progress / 0.8f, 0f, 1f);
        float builtTop = wallsFrac * wallTop;
        bool roofOn = progress >= 0.85f, detailsOn = progress >= 0.95f, finished = progress >= 1f;

        // Plinth: stone from the lowest ground up to the floor.
        var stone = b.Surface(Stone);
        for (int i = 0; i < n; i++)
        {
            var (ax, az) = outline[i]; var (bx, bz) = outline[(i + 1) % n];
            stone.Quad((ax, -plinthDepthM, az), (bx, -plinthDepthM, bz), (bx, 0.05f, bz), (ax, 0.05f, az));
        }

        // Walls, bay by bay.
        int door = 0, back = recipe.Door == "front_and_back" ? BackEdge(outline) : -1;
        for (int e = 0; e < n; e++)
        {
            var (ax, az) = outline[e]; var (bx, bz) = outline[(e + 1) % n];
            float len = MathF.Sqrt((bx - ax) * (bx - ax) + (bz - az) * (bz - az));
            float tx = (bx - ax) / len, tz = (bz - az) / len;
            float yaw = Yaw(tx, tz);
            int bays = Math.Max(1, (int)MathF.Round(len / bayM));
            float bay = len / bays, scale = bay / bayM;
            int doorBay = e == door || e == back ? bays / 2 : -1;
            for (int k = 0; k < bays; k++)
            {
                float px = ax + tx * bay * k, pz = az + tz * bay * k;
                for (int s = 0; s < storeys; s++)
                {
                    float y = s * storeyM;
                    if (y >= builtTop - 1e-3f) break;
                    string piece = s == 0 && k == doorBay ? WallDoor : bay < MinWindowBay ? WallPlain : WallWindow;
                    b.Pieces.Add(new PiecePlacement(piece, px, y, pz, yaw, scale));
                    if (recipe.BeltCourses && s > 0) b.Pieces.Add(new PiecePlacement(BeltCourse, px, y - 0.11f, pz, yaw, scale));
                }
                if (builtTop > 0) b.Pieces.Add(new PiecePlacement(WallBase, px, 0, pz, yaw, scale));
                if (roofOn) b.Pieces.Add(new PiecePlacement(Cornice, px, wallTop, pz, yaw, scale));
            }
            // Outer corner at the start of this edge (the previous edge turns into it).
            var (inX, inZ) = Dir(outline[(e + n - 1) % n], outline[e]);
            bool convex = inX * tz - inZ * tx < 0;
            if (!convex) continue;
            if (recipe.Quoins)
                for (int s = 0; s < storeys && s * storeyM < builtTop - 1e-3f; s++)
                    b.Pieces.Add(new PiecePlacement(Quoin, ax, s * storeyM, az, yaw));
            if (roofOn) b.Pieces.Add(new PiecePlacement(CorniceCorner, ax, wallTop, az, yaw));
        }

        // Roof.
        float tan = MathF.Tan(recipe.Roof.PitchDeg * MathF.PI / 180f), o = d.RoofOverhangM;
        bool gable = recipe.Roof.Type == "gable" && roofRects.Count == 1;
        float ridge = eave;
        if (roofOn)
        {
            var roof = b.Surface(Roof);
            foreach (var (x0, z0, x1, z1) in roofRects)
            {
                float r = gable ? GableRoof(roof, b.Surface(WallMaterial), x0, z0, x1, z1, eave, o, tan)
                                : HipRoof(roof, x0 - o, z0 - o, x1 + o, z1 + o, eave, tan);
                ridge = Math.Max(ridge, r);
                roof.Quad((x0 - o, eave, z0 - o), (x1 + o, eave, z0 - o), (x1 + o, eave, z1 + o), (x0 - o, eave, z1 + o)); // soffit (seen from below)
            }
        }
        else if (builtTop > 0)
        {
            // Open top of the unfinished walls: a timber floor so the inside isn't see-through.
            var floor = b.Surface(Wood);
            float y = MathF.Ceiling(builtTop / storeyM - 1e-3f) * storeyM;
            foreach (var (x0, z0, x1, z1) in roofRects) floor.Quad((x0, y, z1), (x1, y, z1), (x1, y, z0), (x0, y, z0));
        }
        b.RidgeY = ridge;

        // Details.
        if (detailsOn)
        {
            var (fx0, fz) = outline[0]; var (fx1, _) = outline[1];
            float frontLen = fx1 - fx0;
            int frontBays = Math.Max(1, (int)MathF.Round(frontLen / bayM));
            float bay = frontLen / frontBays;
            float doorX = fx0 + bay * (frontBays / 2 + 0.5f);
            int porticoBays = Math.Min(recipe.PorticoBays, frontBays);
            if (porticoBays > 0)
            {
                float halfW = porticoBays * bay / 2 + 0.3f;
                float height = Math.Min(storeys, 2) * storeyM;
                float colZ = fz + PedimentDepth - 0.3f;
                var xs = porticoBays == 1 ? new[] { doorX - halfW + 0.35f, doorX + halfW - 0.35f }
                    : [doorX - halfW + 0.35f, doorX - bay / 2, doorX + bay / 2, doorX + halfW - 0.35f];
                foreach (float cx in xs) b.Pieces.Add(new PiecePlacement(Column, cx, 0, colZ, 0, 1, height / ColumnHeight, 1));
                b.Pieces.Add(new PiecePlacement(Pediment, doorX, height, fz, 0, halfW / PedimentHalfWidth));
            }
            b.Pieces.Add(new PiecePlacement(Steps, doorX, 0, fz, 0));
            if (back >= 0)
            {
                var (bx0, bz) = outline[back]; var (bx1, _) = outline[(back + 1) % n];
                int bb = Math.Max(1, (int)MathF.Round(MathF.Abs(bx1 - bx0) / bayM));
                float bl = (bx1 - bx0) / bb;
                b.Pieces.Add(new PiecePlacement(Steps, bx0 + bl * (bb / 2 + 0.5f), 0, bz, 180));
            }

            if (recipe.Cupola)
            {
                var (x0, z0, x1, z1) = roofRects[0];
                float cx = (x0 + x1) / 2, cz = (z0 + z1) / 2;
                b.Pieces.Add(new PiecePlacement(CupolaPiece, cx, RoofHeightAt(roofRects[0], cx, cz, eave, o, tan, gable) - 0.4f, cz, 0));
            }

            foreach (var (cx, cz) in ChimneySpots(roofRects[0], recipe.Chimneys, gable))
                b.Pieces.Add(new PiecePlacement(Chimney, cx, RoofHeightAt(roofRects[0], cx, cz, eave, o, tan, gable) - 1.6f, cz, 0));
        }

        if (!finished && progress > 0) Scaffolding(b.Surface(Wood), outline, Math.Max(builtTop, 1f) + 1f, storeyM);

        // The far-away block: outline walls up to the eave + the roof.
        var mWall = b.MassingSurface(WallMaterial);
        for (int i = 0; i < n; i++)
        {
            var (ax, az) = outline[i]; var (bx, bz) = outline[(i + 1) % n];
            mWall.Quad((ax, -plinthDepthM, az), (bx, -plinthDepthM, bz), (bx, eave, bz), (ax, eave, az));
        }
        var mRoof = b.MassingSurface(Roof);
        foreach (var (x0, z0, x1, z1) in roofRects)
            if (gable) GableRoof(mRoof, mWall, x0, z0, x1, z1, eave, o, tan); else HipRoof(mRoof, x0 - o, z0 - o, x1 + o, z1 + o, eave, tan);
        return b;
    }

    // ---------------- helpers ----------------

    private static (float X, float Z) Dir((float X, float Z) a, (float X, float Z) b)
    {
        float dx = b.X - a.X, dz = b.Z - a.Z, len = MathF.Sqrt(dx * dx + dz * dz);
        return (dx / len, dz / len);
    }

    /// <summary>Yaw that turns a piece's +X along (tx, tz) and its outer face (+Z) outward.</summary>
    private static float Yaw(float tx, float tz) => MathF.Atan2(-tz, tx) * 180f / MathF.PI;

    private static int BackEdge(List<(float X, float Z)> outline)
    {
        int best = -1;
        float bestLen = 0;
        for (int e = 0; e < outline.Count; e++)
        {
            var (ax, az) = outline[e]; var (bx, bz) = outline[(e + 1) % outline.Count];
            if (MathF.Abs(az - bz) > 1e-3f || bx >= ax) continue; // runs right-to-left = faces the back
            if (ax - bx > bestLen) { bestLen = ax - bx; best = e; }
        }
        return best;
    }

    /// <summary>Hip roof over a rectangle (already including the overhang). Returns the ridge height.</summary>
    private static float HipRoof(MeshBuffer m, float x0, float z0, float x1, float z1, float eave, float tan)
    {
        float w = x1 - x0, d = z1 - z0;
        if (w >= d)
        {
            float h = d / 2 * tan, zc = (z0 + z1) / 2, ra = x0 + d / 2, rb = x1 - d / 2;
            m.Quad((x0, eave, z1), (x1, eave, z1), (rb, eave + h, zc), (ra, eave + h, zc));   // front
            m.Quad((x1, eave, z0), (x0, eave, z0), (ra, eave + h, zc), (rb, eave + h, zc));   // back
            m.Tri((x0, eave, z0), (x0, eave, z1), (ra, eave + h, zc));                          // left hip
            m.Tri((x1, eave, z1), (x1, eave, z0), (rb, eave + h, zc));                          // right hip
            return eave + h;
        }
        else
        {
            float h = w / 2 * tan, xc = (x0 + x1) / 2, ra = z0 + w / 2, rb = z1 - w / 2;
            m.Quad((x1, eave, z1), (x1, eave, z0), (xc, eave + h, ra), (xc, eave + h, rb));   // right
            m.Quad((x0, eave, z0), (x0, eave, z1), (xc, eave + h, rb), (xc, eave + h, ra));   // left
            m.Tri((x0, eave, z1), (x1, eave, z1), (xc, eave + h, rb));                          // front hip
            m.Tri((x1, eave, z0), (x0, eave, z0), (xc, eave + h, ra));                          // back hip
            return eave + h;
        }
    }

    /// <summary>Gable roof with the ridge along the longer side, and the gable end walls. Returns the ridge height.</summary>
    private static float GableRoof(MeshBuffer roof, MeshBuffer wall, float x0, float z0, float x1, float z1, float eave, float o, float tan)
    {
        float w = x1 - x0, d = z1 - z0;
        if (w >= d)
        {
            float h = (d / 2 + o) * tan, zc = (z0 + z1) / 2, X0 = x0 - o, X1 = x1 + o;
            roof.Quad((X0, eave, z1 + o), (X1, eave, z1 + o), (X1, eave + h, zc), (X0, eave + h, zc));
            roof.Quad((X1, eave, z0 - o), (X0, eave, z0 - o), (X0, eave + h, zc), (X1, eave + h, zc));
            wall.Tri((x0, eave, z0 - o), (x0, eave, z1 + o), (x0, eave + h, zc));
            wall.Tri((x1, eave, z1 + o), (x1, eave, z0 - o), (x1, eave + h, zc));
            return eave + h;
        }
        else
        {
            float h = (w / 2 + o) * tan, xc = (x0 + x1) / 2, Z0 = z0 - o, Z1 = z1 + o;
            roof.Quad((x1 + o, eave, Z1), (x1 + o, eave, Z0), (xc, eave + h, Z0), (xc, eave + h, Z1));
            roof.Quad((x0 - o, eave, Z0), (x0 - o, eave, Z1), (xc, eave + h, Z1), (xc, eave + h, Z0));
            wall.Tri((x0 - o, eave, z1), (x1 + o, eave, z1), (xc, eave + h, z1));
            wall.Tri((x1 + o, eave, z0), (x0 - o, eave, z0), (xc, eave + h, z0));
            return eave + h;
        }
    }

    /// <summary>Roof surface height above a plan point inside the main rectangle.</summary>
    private static float RoofHeightAt((float X0, float Z0, float X1, float Z1) r, float x, float z, float eave, float o, float tan, bool gable)
    {
        float w = r.X1 - r.X0, d = r.Z1 - r.Z0;
        float toEdge = gable
            ? (w >= d ? MathF.Min(z - r.Z0, r.Z1 - z) : MathF.Min(x - r.X0, r.X1 - x))
            : MathF.Min(MathF.Min(x - r.X0, r.X1 - x), MathF.Min(z - r.Z0, r.Z1 - z));
        return eave + (toEdge + o) * tan;
    }

    private static IEnumerable<(float X, float Z)> ChimneySpots((float X0, float Z0, float X1, float Z1) r, int count, bool gable)
    {
        if (count <= 0) yield break;
        float w = r.X1 - r.X0, d = r.Z1 - r.Z0, cx = (r.X0 + r.X1) / 2, cz = (r.Z0 + r.Z1) / 2;
        bool alongX = w >= d;
        // Gable roofs: chimneys at the gable ends; hip roofs: on the ridge, a third of the way in.
        float inset = gable ? 1.2f : (alongX ? w : d) / 3;
        float half = (alongX ? w : d) / 2 - inset;
        var ends = count == 1 ? new[] { half } : new[] { -half, half };
        float side = count == 4 ? MathF.Min(1.6f, (alongX ? d : w) / 4) : 0;
        foreach (float a in ends)
            foreach (float s in count == 4 ? new[] { -side, side } : [0f])
                yield return alongX ? (cx + a, cz + s) : (cx + s, cz + a);
    }

    /// <summary>Timber scaffolding around the walls: poles at every bay and boards at each storey.</summary>
    private static void Scaffolding(MeshBuffer m, List<(float X, float Z)> outline, float height, float storeyM)
    {
        const float off = 1.0f, pole = 0.07f;
        int n = outline.Count;
        for (int e = 0; e < n; e++)
        {
            var (ax, az) = outline[e]; var (bx, bz) = outline[(e + 1) % n];
            float len = MathF.Sqrt((bx - ax) * (bx - ax) + (bz - az) * (bz - az));
            float tx = (bx - ax) / len, tz = (bz - az) / len, nx = -tz, nz = tx; // outward
            int poles = Math.Max(1, (int)MathF.Ceiling(len / 3f));
            for (int k = 0; k <= poles; k++)
            {
                float px = ax + tx * len * k / poles + nx * off, pz = az + tz * len * k / poles + nz * off;
                m.Box(px - pole, 0, pz - pole, px + pole, height, pz + pole);
            }
            for (float y = storeyM; y < height; y += storeyM)
            {
                float sx = ax + nx * off, sz = az + nz * off, ex = bx + nx * off, ez = bz + nz * off;
                float x0 = MathF.Min(sx, ex) - 0.3f, x1 = MathF.Max(sx, ex) + 0.3f, z0 = MathF.Min(sz, ez) - 0.3f, z1 = MathF.Max(sz, ez) + 0.3f;
                m.Box(x0, y - 0.05f, z0, x1, y + 0.03f, z1);
            }
        }
    }
}
